USE dbBook;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS PersonPhone;
DROP TABLE IF EXISTS  Phone;
DROP TABLE IF EXISTS  Person;
DROP TABLE IF EXISTS  Address;
DROP TABLE IF EXISTS  Country;
DROP TABLE IF EXISTS Editorial;
DROP TABLE IF EXISTS BookBookFormat;
DROP TABLE IF EXISTS BookFormat;
DROP TABLE IF EXISTS Book;
GO

CREATE TABLE Country (
	 Id INT NOT NULL IDENTITY(1,1) ,
	 Name NVARCHAR(100) NOT NULL UNIQUE,
	 TwoLetterCode NVARCHAR(2) NOT NULL UNIQUE,
	 ThreeLetterCode NVARCHAR(3) NOT NULL UNIQUE,
	 NumericCode NVARCHAR(4) NOT NULL UNIQUE,
	 CONSTRAINT pk_Id_Country PRIMARY KEY(Id)
);
CREATE TABLE Address(
	 Id INT NOT NULL IDENTITY(1,1) ,
	 ZipCode NVARCHAR(19) NULL,
	 City NVARCHAR(50) NULL,
	 Street NVARCHAR(50) NULL,
	 AddressNumber NVARCHAR(10) NULL,
	 FloorNumber NVARCHAR(15) NULL,
	 State NVARCHAR(50) NULL,
	 CountryId INT null,
	 CONSTRAINT pk_Id_Address PRIMARY KEY(Id),
	 CONSTRAINT fk_CountryId_Adress FOREIGN KEY (CountryId) REFERENCES Country(Id)

);

CREATE TABLE Phone(
	 Id INT NOT NULL IDENTITY(1,1),
	 PhoneNumber NVARCHAR(25) NOT NULL,
	 CONSTRAINT pk_Id_phone PRIMARY KEY(Id),
	 CONSTRAINT uk_Number_phone UNIQUE (Number)
);


CREATE TABLE Person (
    Id INT NOT NULL IDENTITY(1,1),
	Guid NVARCHAR(50) NOT NULL,
	FirstName NVARCHAR(35) NOT NULL,
	LastName NVARCHAR(35) NOT NULL,
	NickName NVARCHAR(15) NULL,
	Description NVARCHAR(1000) NULL,
	Email NVARCHAR(100) NULL,
	PhotoUrl NVARCHAR(200),
	AddressId INT NULL,
	CONSTRAINT pk_Id_Person PRIMARY KEY(Id),
	CONSTRAINT fk_AddressId_Person FOREIGN KEY (AddressId) REFERENCES Address(Id)
);

CREATE TABLE PersonPhone(
	  PhoneId INT NOT NULL,
	  PersonId INT NOT NULL FOREIGN KEY REFERENCES Person(Id),
	  CONSTRAINT fk_PhoneId_PersonPhone FOREIGN KEY (PhoneId) REFERENCES Phone(Id)
);

CREATE TABLE Editorial (
	 Id INT NOT NULL IDENTITY(1,1),
     Guid NVARCHAR(50) NOT NULL,
	 Name NVARCHAR(100) NOT NULL,
	 CONSTRAINT pk_Id_Editorial PRIMARY KEY(Id),
	 CONSTRAINT uk_Name_Editorial UNIQUE(Name)
)


CREATE TABLE Author(
	Id INT NOT NULL,
	CONSTRAINT fk_Id_Author FOREIGN KEY(Id) REFERENCES Person(Id)
)

CREATE TABLE Book(
	 Id INT NOT NULL IDENTITY(1,1),
	 Guid NVARCHAR(50) NOT NULL,
	 Title NVARCHAR(50) NOT NULL,
	 Description NVARCHAR(500) NOT NULL,
	 ImageUrl NVARCHAR(100) NULL,
	 CONSTRAINT pk_Id_Book PRIMARY KEY(Id)
);
CREATE TABLE BookFormat(
	 Id INT NOT NULL IDENTITY(1,1),
	 Name NVARCHAR(100) NOT NULL,
	 CONSTRAINT pk_Id_BookFormat PRIMARY KEY(Id),
	 CONSTRAINT uk_Name_BookFormat UNIQUE(Name)
);

CREATE TABLE BookBookFormat(
	BookId INT NOT NULL,
	BookFormatId INT NOT NULL,
	Pages INT NULL,
	Minutes INT NULL,
	Price Decimal NOT NULL,
	CONSTRAINT fk_BookId_BookBookFormat FOREIGN KEY(BookId) REFERENCES Book(Id),
	CONSTRAINT fk_BookFormatId_BookBookFormat FOREIGN KEY(BookFormatId) REFERENCES BookFormat(Id)
)

CREATE TABLE Test(
	 Id INT NOT NULL IDENTITY(1,1),
	 Name NVARCHAR(100) NOT NULL,
	 CONSTRAINT pk_Id_Test PRIMARY KEY(Id),
) 
